# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62e72686e8226788a94b54f5c7085a22ed0917f8860dd8d3b89cb5c063b6456176b1014974c5d833f72c24ed3c7ec89790f6f6bab89669ef67a33ec50401dbf8

test:
  secret_key_base: 1781256062bc834b038d030e0c2abc4a8278736b362312d154827bc04a65eb68f9ba8cd9e2473c78ccbbfce6fe10928d95f951c8eeaf6fe983bddcc53944deef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
